version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file: ./api-gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - post-service
      - comment-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file: ./user-service/.env
    ports:
      - "50051:50051"
    depends_on:
      - postgres-user

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    env_file: ./post-service/.env
    ports:
      - "50052:50052"
    depends_on:
      - postgres-post

  comment-service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    env_file: ./comment-service/.env
    ports:
      - "50053:50053"
    depends_on:
      - postgres-comment

  postgres-user:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lemontea
      POSTGRES_DB: blog_user_service
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres-post:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lemontea
      POSTGRES_DB: blog_post_service
    volumes:
      - post_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  postgres-comment:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lemontea
      POSTGRES_DB: blog_comment_service
    volumes:
      - comment_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

volumes:
  user_data:
  post_data:
  comment_data:
